/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.App;
import Model.Dosen;
import Model.Kelas;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author cleanrun
 */
public class FormSetDosen extends javax.swing.JFrame {

    /**
     * Creates new form FormAddDosen
     */
    public FormSetDosen(ArrayList<Dosen> listdsn, ArrayList<Kelas> listkelas) {
        initComponents();
        setLocationRelativeTo(null);
        this.listdsn = listdsn;
        this.listkelas = listkelas;
        setComboBoxDosen();
        setComboBoxKelas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxListDosen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxListKelas = new javax.swing.JComboBox<>();
        jButtonSet = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SET DOSEN TO KELAS");

        jLabel2.setText("Select Dosen : ");

        jComboBoxListDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListDosenActionPerformed(evt);
            }
        });

        jLabel3.setText("Select Kelas :");

        jButtonSet.setText("Set");
        jButtonSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxListDosen, 0, 115, Short.MAX_VALUE)
                            .addComponent(jComboBoxListKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 115, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addGap(18, 18, 18)
                .addComponent(jButtonSet)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxListDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxListKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSet)
                    .addComponent(jButtonBack))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSetActionPerformed

    private void jComboBoxListDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxListDosenActionPerformed

    public void setActionListener(ActionListener a){
        jButtonBack.addActionListener(a);
        jButtonSet.addActionListener(a);
    }
    
    private void setComboBoxDosen(){
        for(Dosen d : this.listdsn){
            jComboBoxListDosen.addItem(d.getNama());
        }
    }
    
    private void setComboBoxKelas(){
        for(Kelas k : this.listkelas){
            jComboBoxListKelas.addItem(k.getNamaKelas());
        }
    }
    
    public Dosen getComboBoxDosen(){
        for(Dosen d : this.listdsn){
            if(jComboBoxListDosen.getSelectedItem() == d.getNama()){
                return d;
            }
        }
        return null;
    }
    
    public Kelas getComboBoxKelas(){
        for(Kelas k : this.listkelas){
            if(jComboBoxListKelas.getSelectedItem() == k.getNamaKelas()){
                return k;
            }
        }
        return null;
    }
    
    public JButton getButtonSet(){
        return jButtonSet;
    }
    
    public JButton getButtonBack(){
        return jButtonBack;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSet;
    private javax.swing.JComboBox<String> jComboBoxListDosen;
    private javax.swing.JComboBox<String> jComboBoxListKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Dosen> listdsn;
    private ArrayList<Kelas> listkelas;
}
