/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.App; // buat combobox
import Model.Dosen;
import Model.Matakuliah;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author cleanrun
 */
public class FormKelas extends javax.swing.JFrame {

    /**
     * Creates new form FormKelasFr
     */
    public FormKelas(ArrayList<Matakuliah> listmk, ArrayList<Dosen> listdsn) {
        initComponents();
        setLocationRelativeTo(null);
        this.listmk = listmk;
        this.listdsn = listdsn;
        setComboBoxMk();
        setComboBoxDosen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxMk = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxDosen = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerMhs = new javax.swing.JSpinner();
        jButtonInput = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxMk.setMaximumRowCount(100);

        jLabel3.setText("Dosen :");

        jLabel4.setText("Jumlah Mahasiswa :");

        jSpinnerMhs.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        jButtonInput.setText("Input");

        jButtonBack.setText("Back");

        jLabel1.setText("Nama Kelas : ");

        jLabel2.setText("Matakuliah : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNama)
                            .addComponent(jComboBoxMk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxDosen, 0, 135, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBack)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(jButtonInput)
                                .addGap(17, 17, 17)))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInput)
                    .addComponent(jButtonBack))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setActionListener(ActionListener a){
        jButtonInput.addActionListener(a);
        jButtonBack.addActionListener(a);
    }
    
    public String getTextFieldNama(){
        return jTextFieldNama.getText();
    }
    
    public int getSpinnerSks(){
        return (int) jSpinnerMhs.getValue();
    }
    
    private void setComboBoxMk(){
        for(Matakuliah m : this.listmk){
            jComboBoxMk.addItem(m.getNamaMk());
        }
    }
    
    private void setComboBoxDosen(){
        for(Dosen d : this.listdsn){
            jComboBoxDosen.addItem(d.getNama());
        }
    }
    
    public Dosen getComboBoxDosen(){
        for(Dosen d : listdsn){
            if(jComboBoxDosen.getSelectedItem() == d.getNama()){
                return d;
            }
        }
        return null;
    }
    
    public Matakuliah getComboBoxMk(){
        for(Matakuliah m : listmk){
            if(jComboBoxMk.getSelectedItem() == m.getNamaMk()){
                return m;
            }
        }
        return null;
    }
    
    public JButton getButtonInput(){
        return jButtonInput;
    }
    
    public JButton getButtonBack(){
        return jButtonBack;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonInput;
    private javax.swing.JComboBox<String> jComboBoxDosen;
    private javax.swing.JComboBox<String> jComboBoxMk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSpinnerMhs;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Matakuliah> listmk;
    private ArrayList<Dosen> listdsn;
}
