/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;

public class FormMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form testgui
     */
    public FormMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inpNamaMahasiswa = new javax.swing.JTextField();
        jLabelNama = new javax.swing.JLabel();
        jLabelUmur = new javax.swing.JLabel();
        jLabelNim = new javax.swing.JLabel();
        inpNim = new javax.swing.JTextField();
        jLabelFakultas = new javax.swing.JLabel();
        inpFakultas = new javax.swing.JTextField();
        jLabelSemester = new javax.swing.JLabel();
        inpSemester = new javax.swing.JTextField();
        jLabelSks = new javax.swing.JLabel();
        BtnInput = new javax.swing.JButton();
        jSpinnerUmur = new javax.swing.JSpinner();
        jSpinnerSks = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(15, 15));

        inpNamaMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNamaMahasiswaActionPerformed(evt);
            }
        });

        jLabelNama.setText("Nama Mahasiswa : ");

        jLabelUmur.setText("Umur : ");

        jLabelNim.setText("NIM :");

        inpNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNimActionPerformed(evt);
            }
        });

        jLabelFakultas.setText("Fakultas : ");

        inpFakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpFakultasActionPerformed(evt);
            }
        });

        jLabelSemester.setText("Semester : ");

        inpSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpSemesterActionPerformed(evt);
            }
        });

        jLabelSks.setText("SKS : ");

        BtnInput.setText("Input");
        BtnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInputActionPerformed(evt);
            }
        });

        jSpinnerUmur.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerSks.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNama)
                    .addComponent(jLabelUmur)
                    .addComponent(jLabelNim)
                    .addComponent(jLabelFakultas)
                    .addComponent(jLabelSemester)
                    .addComponent(jLabelSks))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inpSemester)
                            .addComponent(inpFakultas)
                            .addComponent(inpNim)
                            .addComponent(inpNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerSks, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(BtnInput)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUmur)
                    .addComponent(jSpinnerUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNim)
                    .addComponent(inpNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFakultas)
                    .addComponent(inpFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSemester))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSks)
                    .addComponent(jSpinnerSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(BtnInput)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpNamaMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNamaMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNamaMahasiswaActionPerformed

    private void inpNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNimActionPerformed

    private void inpFakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpFakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpFakultasActionPerformed

    private void inpSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpSemesterActionPerformed

    private void BtnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMahasiswa().setVisible(true);
            }
        });
    }

    public String getInpNamaMahasiswa(){
        return inpNamaMahasiswa.getText();
    }
    
    public int getJSpinnerUmur(){
        return (int) jSpinnerUmur.getValue();
    }
    
    public String getInpNim(){
        return inpNim.getText();
    }
    
    public String getInpFakultas(){
        return inpFakultas.getText();
    }
    
    public int getInpSemester(){
        return Integer.parseInt(inpSemester.getText());
    }
    
    public int getJSpinnerSks(){
        return (int) jSpinnerSks.getValue();
    }
    
    public void btnInputPerformed(ActionListener a){
        BtnInput.addActionListener(a);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInput;
    private javax.swing.JTextField inpFakultas;
    private javax.swing.JTextField inpNamaMahasiswa;
    private javax.swing.JTextField inpNim;
    private javax.swing.JTextField inpSemester;
    private javax.swing.JLabel jLabelFakultas;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNim;
    private javax.swing.JLabel jLabelSemester;
    private javax.swing.JLabel jLabelSks;
    private javax.swing.JLabel jLabelUmur;
    private javax.swing.JSpinner jSpinnerSks;
    private javax.swing.JSpinner jSpinnerUmur;
    // End of variables declaration//GEN-END:variables
}
